import {
  Activity,
  BadgeCheck,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  FileCheck2,
  FileSearch,
  Gauge,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  Lightbulb,
  ListChecks,
  MonitorCog,
  Network,
  PackageCheck,
  PanelsTopLeft,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
} from "lucide-react";

export const serviceIcons = {
  Activity,
  BadgeCheck,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  FileCheck2,
  FileSearch,
  Gauge,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  Lightbulb,
  ListChecks,
  MonitorCog,
  Network,
  PackageCheck,
  PanelsTopLeft,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
};

export function getServiceIcon(iconName) {
  return serviceIcons[iconName] || Sparkles;
}